from __future__ import annotations

from typing import Any, Protocol

from ..import_management import ImportBatch, SnapshotRecord, SourceSnapshot
from ..run_context import EngineRun, SourceFetch


class RecordRepository(Protocol):
    def add(self, record_id: str, payload: str) -> None: ...
    def get(self, record_id: str) -> dict[str, Any] | None: ...


class ImportBatchRepository(Protocol):
    def add(self, batch: ImportBatch) -> None: ...
    def get(self, import_batch_id: str) -> ImportBatch | None: ...
    def update(self, batch: ImportBatch) -> None: ...


class SnapshotRepository(Protocol):
    def add(self, snapshot: SourceSnapshot, records: tuple[SnapshotRecord, ...]) -> None: ...
    def get(self, snapshot_id: str) -> SourceSnapshot | None: ...
    def records(self, snapshot_id: str) -> tuple[SnapshotRecord, ...]: ...
    def latest(self, source_system: str, dataset_type: str, source_period: str | None) -> SourceSnapshot | None: ...


class SourceFetchRepository(Protocol):
    def add(self, fetch: SourceFetch) -> None: ...
    def get(self, source_fetch_id: str) -> SourceFetch | None: ...


class EngineRunRepository(Protocol):
    def add(self, run: EngineRun) -> None: ...
    def get(self, engine_run_id: str) -> EngineRun | None: ...
